<?php

declare(strict_types=1);

namespace Strapi\Core\Services\Server;

use Strapi\Core\Strapi;
use Symfony\Component\Process\Process;

/**
 * Port of packages/core/core/src/services/server/http-server.ts.
 *
 * Node's `http.createServer` becomes PHP's built-in web server (`php -S host:port -t public <router>`)
 * run through symfony/process: it is the simplest option that needs no extension and matches how
 * a project is deployed (FPM/FrankenPHP execute `public/index.php` per request; the built-in server
 * does the same). The router script is the project's `public/index.php` when it exists, otherwise a
 * generated `.tmp/strapi-router.php` that boots Strapi and calls `server.handle()`.
 *
 * Because the built-in server runs requests in a child process, the Strapi instance that called
 * `listen()` only logs the startup message; each request boots its own instance (schema sync is a
 * hash check after the first boot). For a persistent process use FrankenPHP worker mode with the
 * same `public/index.php`.
 */
final class HttpServer
{
    private ?Process $process = null;

    public function __construct(private readonly Strapi $strapi, public readonly Server $server)
    {
    }

    public static function createHTTPServer(Strapi $strapi, Server $server): self
    {
        return new self($strapi, $server);
    }

    public function listening(): bool
    {
        return $this->process !== null && $this->process->isRunning();
    }

    /** @param callable(): void|null $onListen */
    public function listen(string $host, int $port, ?callable $onListen = null): void
    {
        $root = $this->strapi->dirs()->root;
        $public = $this->strapi->dirs()->public;
        $router = $public . '/index.php';

        if (!is_file($router)) {
            $router = $this->writeRouterScript($root);
        }

        if (self::portInUse($host, $port)) {
            $this->strapi->stopWithError(new \RuntimeException("The port {$port} is already used by another application."));
        }

        $php = PHP_BINARY;
        $this->process = new Process([$php, '-S', "{$host}:{$port}", '-t', $public, $router], $root, [
            ...array_filter(getenv(), 'is_string'),
            'STRAPI_APP_DIR' => $root,
            'PHP_CLI_SERVER_WORKERS' => (string) ((int) ($this->strapi->config()->get('server.http.workers', 4))),
        ], null, null);

        $this->process->start(function (string $type, string $buffer): void {
            fwrite($type === Process::ERR ? STDERR : STDOUT, $buffer);
        });

        // wait for the socket
        $deadline = microtime(true) + 5;
        while (microtime(true) < $deadline && !self::portInUse($host === '0.0.0.0' ? '127.0.0.1' : $host, $port)) {
            usleep(50_000);
            if (!$this->process->isRunning()) {
                $this->strapi->stopWithError(new \RuntimeException('The built-in server stopped unexpectedly: ' . $this->process->getErrorOutput()));
            }
        }

        if ($onListen !== null) {
            $onListen();
        }

        $this->process->wait();
    }

    public static function portInUse(string $host, int $port): bool
    {
        $socket = @stream_socket_client("tcp://{$host}:{$port}", $errno, $errstr, 0.2);
        if ($socket === false) {
            return false;
        }
        fclose($socket);

        return true;
    }

    private function writeRouterScript(string $root): string
    {
        $dir = $root . '/.tmp';
        if (!is_dir($dir)) {
            mkdir($dir, 0o777, true);
        }
        $file = $dir . '/strapi-router.php';
        $autoload = self::findAutoload($root);

        $script = <<<PHP
<?php
// generated by strapi/core HttpServer: boots Strapi and handles the request (built-in server mode)
declare(strict_types=1);
require {$autoload};
\$public = {$this->export($this->strapi->dirs()->public)};
\$path = parse_url(\$_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH) ?? '/';
if (\$path !== '/' && is_file(\$public . \$path)) {
    return false; // serve the static file
}
\$strapi = \\Strapi\\Core\\Core::createStrapi(['appDir' => {$this->export($root)}])->load();
\\Strapi\\Core\\Services\\Server\\HttpServer::emit(\$strapi->server()->handle(\\Strapi\\Core\\Services\\Server\\HttpServer::requestFromGlobals()));
PHP;
        file_put_contents($file, $script);

        return $file;
    }

    private function export(string $value): string
    {
        return var_export($value, true);
    }

    private static function findAutoload(string $root): string
    {
        foreach ([$root . '/vendor/autoload.php', dirname(__DIR__, 5) . '/vendor/autoload.php', dirname(__DIR__, 7) . '/vendor/autoload.php'] as $candidate) {
            if (is_file($candidate)) {
                return var_export($candidate, true);
            }
        }

        return var_export($root . '/vendor/autoload.php', true);
    }

    /** Build the PSR-7 request from PHP globals (nyholm/psr7-server). */
    public static function requestFromGlobals(): \Psr\Http\Message\ServerRequestInterface
    {
        $factory = new \Nyholm\Psr7\Factory\Psr17Factory();
        $creator = new \Nyholm\Psr7Server\ServerRequestCreator($factory, $factory, $factory, $factory);

        return $creator->fromGlobals();
    }

    /** Send a PSR-7 response with PHP's SAPI. */
    public static function emit(\Psr\Http\Message\ResponseInterface $response): void
    {
        if (!headers_sent()) {
            http_response_code($response->getStatusCode());
            // the response's Content-Type is final: PHP must not append `;charset=` (default_charset)
            // to `text/*` types as Koa never does (`text/event-stream` stays as set)
            $defaultCharset = ini_get('default_charset');
            ini_set('default_charset', '');
            try {
                foreach ($response->getHeaders() as $name => $values) {
                    $first = true;
                    foreach ($values as $value) {
                        header("{$name}: {$value}", $first);
                        $first = false;
                    }
                }
            } finally {
                ini_set('default_charset', $defaultCharset === false ? 'UTF-8' : $defaultCharset);
            }
        }

        $body = $response->getBody();
        if ($body->isSeekable()) {
            $body->rewind();
        }
        while (!$body->eof()) {
            echo $body->read(65536);
        }
    }

    public function destroy(): void
    {
        if ($this->process !== null && $this->process->isRunning()) {
            $this->process->stop(2);
        }
        $this->process = null;
    }
}
