#!/usr/bin/env node
// Regenerates ../ZodOracleCases.php from the real zod library.
//
//   mkdir /tmp/zod-oracle && cd /tmp/zod-oracle && npm install zod@4.4.3
//   NODE_PATH=/tmp/zod-oracle/node_modules node generate.js > ../ZodOracleCases.php
const { z } = require('zod/v4');
const cases = require('./cases.js')(z);
const jsonSchemaCases = require('./json-schema-cases.js')(z);

const MAX_SAFE = Number.MAX_SAFE_INTEGER;

const phpString = (s) => "'" + s.replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";

const phpNumber = (n) => {
  if (Number.isNaN(n)) return 'NAN';
  if (n === Infinity) return 'INF';
  if (n === -Infinity) return '-INF';
  if (Number.isInteger(n) && Math.abs(n) <= MAX_SAFE) return String(n);
  const s = String(n);
  return /[.eE]/.test(s) ? s : s + '.0';
};

// JS value -> PHP literal. `top` objects: {} becomes `new \stdClass()` for inputs.
const toPhp = (v, mode, indent = '') => {
  if (v && v.__raw) return mode === 'input' ? v.php : toPhp(v.js, mode, indent);
  if (v === undefined) return mode === 'input' ? 'Undefined::Value' : 'null';
  if (v === null) return 'null';
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'number') return phpNumber(v);
  if (typeof v === 'string') return phpString(v);
  if (Array.isArray(v)) return '[' + v.map((x) => toPhp(x === undefined && mode !== 'input' ? null : x, mode, indent)).join(', ') + ']';
  if (typeof v === 'object') {
    const keys = Object.keys(v).filter((k) => mode === 'input' || v[k] !== undefined);
    if (keys.length === 0) return mode === 'input' ? 'new \\stdClass()' : '[]';
    return '[' + keys.map((k) => phpString(k) + ' => ' + toPhp(v[k], mode, indent)).join(', ') + ']';
  }
  throw new Error('Cannot convert ' + typeof v);
};

const plain = (v) => (v && v.__raw ? v.js : v);

let out = `<?php

declare(strict_types=1);

namespace Strapi\\Utils\\Tests\\Zod;

use Strapi\\Utils\\Zod as z;
use Strapi\\Utils\\Zod\\Undefined;
use Strapi\\Utils\\Zod\\ZodIssueCode;
use Strapi\\Utils\\Zod\\ZodRegistry;
use Strapi\\Utils\\Zod\\ZodType;

/**
 * GENERATED by tests/Zod/oracle/generate.js from tests/Zod/oracle/cases.js: \`safeParse()\`
 * results of zod 4.4.3 itself. Do not edit by hand; edit cases.js and regenerate.
 *
 * Each case: [schema factory, input, expected] where expected is
 * \`['success' => true, 'data' => ...]\` or \`['success' => false, 'issues' => [...]]\`.
 */
final class ZodOracleCases
{
    /** @return iterable<string, array{\\Closure(): ZodType, mixed, array<string, mixed>}> */
    public static function cases(): iterable
    {
`;

for (const c of cases) {
  c.inputs.forEach((input, i) => {
    const r = c.js.safeParse(plain(input));
    const expected = r.success
      ? `['success' => true, 'data' => ${toPhp(r.data, 'output')}]`
      : `['success' => false, 'issues' => ${toPhp(JSON.parse(JSON.stringify(r.error.issues)), 'output')}]`;
    const label = `${c.name} #${i}`;
    out += `        yield ${phpString(label)} => [static fn (): ZodType => ${c.php}, ${toPhp(input, 'input')}, ${expected}];\n`;
  });
}

out += `    }

    /** @return iterable<string, array{\\Closure(): (ZodType|ZodRegistry), \\Closure(): array<string, mixed>, string}> */
    public static function jsonSchemaCases(): iterable
    {
`;
for (const c of jsonSchemaCases) {
  const json = JSON.stringify(z.toJSONSchema(c.js, c.params ?? {}));
  out += `        yield ${phpString(c.name)} => [static fn (): ZodType|ZodRegistry => ${c.php}, static fn (): array => ${c.phpParams ?? '[]'}, ${phpString(json)}];\n`;
}

out += `    }

    /** \`const Cat = z.lazy(() => z.object({ name: z.string(), children: z.array(Cat).optional() }))\` */
    public static function category(): ZodType
    {
        $category = null;
        $category = z::lazy(static function () use (&$category): ZodType {
            assert($category instanceof ZodType);

            return z::object(['name' => z::string(), 'children' => z::array($category)->optional()]);
        });

        return $category;
    }

    /** \`const Cat = z.lazy(() => z.object({ name: z.string(), children: z.array(Cat) }))\` */
    public static function cat(): ZodType
    {
        $cat = null;
        $cat = z::lazy(static function () use (&$cat): ZodType {
            assert($cat instanceof ZodType);

            return z::object(['name' => z::string(), 'children' => z::array($cat)]);
        });

        return $cat;
    }

    public static function node(): ZodType
    {
        static $node = null;

        return $node ??= self::category();
    }

    private static ?ZodType $article = null;

    private static ?ZodRegistry $registry = null;

    public static function article(): ZodType
    {
        return self::$article ??= z::object(['title' => z::string()]);
    }

    /** The registry of json-schema-cases.js: Article, and B referencing Article and itself. */
    public static function registry(): ZodRegistry
    {
        if (self::$registry === null) {
            $b = null;
            $b = z::object([
                'a' => self::article(),
                'list' => z::array(self::article()),
                'self' => z::lazy(static function () use (&$b): ZodType {
                    assert($b instanceof ZodType);

                    return $b;
                })->optional(),
            ]);
            self::$registry = z::registry()->add(self::article(), ['id' => 'Article'])->add($b, ['id' => 'B']);
        }

        return self::$registry;
    }

    private static ?ZodType $metaNested = null;

    private static ?ZodRegistry $metaRegistry = null;

    /** \`z.object({ value: z.string() }).meta({ id: 'MetaNested', description: 'nested' })\` */
    public static function metaNested(): ZodType
    {
        return self::$metaNested ??= z::object(['value' => z::string()])->meta(['id' => 'MetaNested', 'description' => 'nested']);
    }

    /** The metaRegistry of json-schema-cases.js: entries whose nested schemas carry \`.meta({ id })\`. */
    public static function metaRegistry(): ZodRegistry
    {
        return self::$metaRegistry ??= z::registry()
            ->add(z::object(['nested' => self::metaNested(), 'other' => z::object(['inner' => z::string()->meta(['id' => 'MetaInner'])])]), ['id' => 'MetaRoot'])
            ->add(z::object(['again' => self::metaNested()]), ['id' => 'MetaOther']);
    }
}
`;

process.stdout.write(out);
