<?php

declare(strict_types=1);

namespace Strapi\Admin\Services;

use Strapi\Admin\Domain\Permission\Permission as PermissionDomain;
use Strapi\Admin\Validation\Permission as PermissionValidation;
use Strapi\Core\Strapi;
use Strapi\Utils\Errors\ApplicationError;
use Strapi\Utils\Hooks;
use Strapi\Utils\Hooks\AsyncSeriesWaterfallHook;
use Strapi\Utils\Primitives\Arrays;
use Strapi\Utils\Primitives\Dates;
use Strapi\Utils\Primitives\Strings;

/**
 * Port of server/src/services/role.ts.
 */
final class Role
{
    /** services/constants.ts */
    public const string SUPER_ADMIN_CODE = 'strapi-super-admin';

    public const string CONTENT_TYPE_SECTION = 'contentTypes';

    public const array ACTIONS = [
        'publish' => 'plugin::content-manager.explorer.publish',
    ];

    public const array COMPARABLE_FIELDS = ['conditions', 'properties', 'subject', 'action', 'actionParameters'];

    /** @var array{willResetSuperAdminPermissions: AsyncSeriesWaterfallHook, willValidateUpdatePermissions: AsyncSeriesWaterfallHook} */
    public readonly array $hooks;

    /** @var array{superAdminCode: string} */
    public readonly array $constants;

    public function __construct(private readonly Strapi $strapi)
    {
        $this->hooks = [
            'willResetSuperAdminPermissions' => Hooks::createAsyncSeriesWaterfallHook(),
            'willValidateUpdatePermissions' => Hooks::createAsyncSeriesWaterfallHook(),
        ];
        $this->constants = ['superAdminCode' => self::SUPER_ADMIN_CODE];
    }

    private function permissionService(): Permission
    {
        /** @var Permission $service */
        $service = $this->strapi->service('admin::permission');

        return $service;
    }

    /**
     * `omit(['users', 'permissions'])`
     *
     * @param array<string, mixed>|null $role
     * @return array<string, mixed>|null
     */
    public function sanitizeRole(?array $role): ?array
    {
        if ($role === null) {
            return null;
        }

        unset($role['users'], $role['permissions']);

        return $role;
    }

    /**
     * `JSON.parse(JSON.stringify(pick(COMPARABLE_FIELDS)))`: drops undefined, normalizes key order.
     *
     * @param array<string, mixed> $permission
     */
    private static function comparable(array $permission): mixed
    {
        $picked = [];
        foreach (self::COMPARABLE_FIELDS as $field) {
            if (array_key_exists($field, $permission)) {
                $picked[$field] = $permission[$field];
            }
        }

        return self::normalize($picked);
    }

    private static function normalize(mixed $value): mixed
    {
        if (!is_array($value)) {
            return $value;
        }
        if (array_is_list($value)) {
            return array_map(self::normalize(...), $value);
        }
        ksort($value);

        return array_map(self::normalize(...), $value);
    }

    /**
     * Compare two permissions.
     *
     * @param array<string, mixed> $p1
     * @param array<string, mixed> $p2
     */
    public static function arePermissionsEqual(array $p1, array $p2): bool
    {
        if (($p1['action'] ?? null) === ($p2['action'] ?? null)) {
            return self::comparable($p1) == self::comparable($p2);
        }

        return false;
    }

    /**
     * Create and save a role in database.
     *
     * @param array<string, mixed> $attributes
     * @return array<string, mixed>
     */
    public function create(array $attributes): array
    {
        $alreadyExists = $this->exists(['name' => $attributes['name'] ?? null]);

        if ($alreadyExists) {
            throw new ApplicationError(sprintf(
                'The name must be unique and a role with name `%s` already exists.',
                (string) ($attributes['name'] ?? 'undefined'),
            ));
        }

        $autoGeneratedCode = Strings::kebabCase((string) ($attributes['name'] ?? '')) . '-' . Dates::timestampCode();

        $code = $attributes['code'] ?? null;
        $rolesWithCode = [
            ...$attributes,
            'code' => is_string($code) && $code !== '' ? $code : $autoGeneratedCode,
        ];

        $result = $this->strapi->db()->query('admin::role')->create(['data' => $rolesWithCode]);
        $this->strapi->eventHub()->emit('role.create', ['role' => $this->sanitizeRole($result)]);

        return $result;
    }

    /**
     * Find a role in database.
     *
     * @param array<string, mixed> $params
     * @return array<string, mixed>|null
     */
    public function findOne(array $params = [], mixed $populate = null): ?array
    {
        $query = ['where' => $params];
        if ($populate !== null) {
            $query['populate'] = $populate;
        }

        return $this->strapi->db()->query('admin::role')->findOne($query);
    }

    /**
     * Find a role in database with usersCount.
     *
     * @param array<string, mixed> $params
     * @return array<string, mixed>|null
     */
    public function findOneWithUsersCount(array $params = [], mixed $populate = null): ?array
    {
        $role = $this->findOne($params, $populate);

        if ($role !== null) {
            $role['usersCount'] = $this->getUsersCount($role['id']);
        }

        return $role;
    }

    /**
     * Find roles in database.
     *
     * @param array<string, mixed> $params
     * @return list<array<string, mixed>>
     */
    public function find(array $params = [], mixed $populate = null): array
    {
        $query = ['where' => $params];
        if ($populate !== null) {
            $query['populate'] = $populate;
        }

        return array_values($this->strapi->db()->query('admin::role')->findMany($query));
    }

    /**
     * Find all roles in database.
     *
     * @param array<string, mixed> $params
     * @return list<array<string, mixed>>
     */
    public function findAllWithUsersCount(array $params = []): array
    {
        /** @var \Strapi\Core\Services\QueryParams $queryParams */
        $queryParams = $this->strapi->get('query-params');
        $roles = $this->strapi->db()->query('admin::role')->findMany($queryParams->transform('admin::role', $params));

        foreach ($roles as $i => $role) {
            $roles[$i]['usersCount'] = $this->getUsersCount($role['id']);
        }

        return array_values($roles);
    }

    /**
     * Update a role in database.
     *
     * @param array<string, mixed> $params
     * @param array<string, mixed> $attributes
     * @return array<string, mixed>|null
     */
    public function update(array $params, array $attributes): ?array
    {
        $sanitizedAttributes = $attributes;
        unset($sanitizedAttributes['code']);

        if (array_key_exists('id', $params) && array_key_exists('name', $sanitizedAttributes)) {
            $alreadyExists = $this->exists([
                'name' => $sanitizedAttributes['name'],
                'id' => ['$ne' => $params['id']],
            ]);
            if ($alreadyExists) {
                throw new ApplicationError(sprintf(
                    'The name must be unique and a role with name `%s` already exists.',
                    (string) $sanitizedAttributes['name'],
                ));
            }
        }

        $result = $this->strapi->db()->query('admin::role')->update(['where' => $params, 'data' => $sanitizedAttributes]);

        $this->strapi->eventHub()->emit('role.update', ['role' => $this->sanitizeRole($result)]);

        return $result;
    }

    /**
     * Check if a role exists in database.
     *
     * @param array<string, mixed> $params
     */
    public function exists(array $params = []): bool
    {
        $count = $this->strapi->db()->query('admin::role')->count(['where' => $params]);

        return $count > 0;
    }

    /**
     * Count the number of roles based on search params.
     *
     * @param array<string, mixed> $params
     */
    public function count(array $params = []): int
    {
        return $this->strapi->db()->query('admin::role')->count($params);
    }

    /**
     * Check if the given roles id can be deleted safely, throw otherwise.
     *
     * @param list<int|string> $ids
     */
    public function checkRolesIdForDeletion(array $ids = []): void
    {
        $superAdminRole = $this->getSuperAdmin();

        if ($superAdminRole !== null && Arrays::includesString($ids, $superAdminRole['id'])) {
            throw new ApplicationError('You cannot delete the super admin role');
        }

        foreach ($ids as $roleId) {
            $usersCount = $this->getUsersCount($roleId);
            if ($usersCount !== 0) {
                throw new ApplicationError('Some roles are still assigned to some users');
            }
        }
    }

    /**
     * Delete roles in database if they have no user assigned.
     *
     * @param list<int|string> $ids
     * @return list<array<string, mixed>>
     */
    public function deleteByIds(array $ids = []): array
    {
        $this->checkRolesIdForDeletion($ids);

        $this->permissionService()->deleteByRolesIds($ids);

        $deletedRoles = [];
        foreach ($ids as $id) {
            $deletedRole = $this->strapi->db()->query('admin::role')->delete(['where' => ['id' => $id]]);

            if ($deletedRole !== null) {
                $this->strapi->eventHub()->emit('role.delete', ['role' => $deletedRole]);
                $deletedRoles[] = $deletedRole;
            }
        }

        return $deletedRoles;
    }

    /** Count the number of users for some roles. */
    public function getUsersCount(mixed $roleId): int
    {
        return $this->strapi->db()->query('admin::user')->count(['where' => ['roles' => ['id' => $roleId]]]);
    }

    /**
     * Returns admin role.
     *
     * @return array<string, mixed>|null
     */
    public function getSuperAdmin(): ?array
    {
        return $this->findOne(['code' => self::SUPER_ADMIN_CODE]);
    }

    /**
     * Returns admin role with usersCount.
     *
     * @return array<string, mixed>|null
     */
    public function getSuperAdminWithUsersCount(): ?array
    {
        return $this->findOneWithUsersCount(['code' => self::SUPER_ADMIN_CODE]);
    }

    /** Create superAdmin, Author and Editor role if no role already exist. */
    public function createRolesIfNoneExist(): void
    {
        $someRolesExist = $this->exists();
        if ($someRolesExist) {
            return;
        }

        $actionProvider = $this->permissionService()->actionProvider;

        $allActions = $actionProvider->values();
        $contentTypesActions = array_values(array_filter($allActions, static fn (array $a): bool => ($a['section'] ?? null) === 'contentTypes'));

        // create 3 roles
        $superAdminRole = $this->create([
            'name' => 'Super Admin',
            'code' => 'strapi-super-admin',
            'description' => 'Super Admins can access and manage all features and settings.',
        ]);

        /** @var User $userService */
        $userService = $this->strapi->service('admin::user');
        $userService->assignARoleToAll($superAdminRole['id']);

        $editorRole = $this->create([
            'name' => 'Editor',
            'code' => 'strapi-editor',
            'description' => 'Editors can manage and publish contents including those of other users.',
        ]);

        $authorRole = $this->create([
            'name' => 'Author',
            'code' => 'strapi-author',
            'description' => 'Authors can manage the content they have created.',
        ]);

        // create content-type permissions for each role
        // Exclude non-displayed content types (e.g. plugin::users-permissions.role) from Editor/Author
        // since those types are in explorer.read subjects only for super admin relation reads.
        $nonDisplayedUids = [];
        foreach ($this->strapi->contentTypes() as $ct) {
            if (($ct->pluginOptions['content-manager']['visible'] ?? null) === false) {
                $nonDisplayedUids[] = $ct->uid;
            }
        }

        /** @var ContentType $contentTypeService */
        $contentTypeService = $this->strapi->service('admin::content-type');
        $editorPermissions = $contentTypeService->getPermissionsWithNestedFields($contentTypesActions, [
            'restrictedSubjects' => ['plugin::users-permissions.user', ...$nonDisplayedUids],
        ]);

        $authorPermissions = [];
        foreach ($editorPermissions as $permission) {
            if (($permission['action'] ?? null) === self::ACTIONS['publish']) {
                continue;
            }
            $authorPermissions[] = PermissionDomain::create([...$permission, 'conditions' => ['admin::is-creator']]);
        }

        array_push($editorPermissions, ...$this->getDefaultPluginPermissions());
        array_push($authorPermissions, ...$this->getDefaultPluginPermissions(['isAuthor' => true]));

        // assign permissions to roles
        $this->addPermissions($editorRole['id'], $editorPermissions);
        $this->addPermissions($authorRole['id'], $authorPermissions);
    }

    /**
     * @param array{isAuthor?: bool} $options
     * @return list<array<string, mixed>>
     */
    public function getDefaultPluginPermissions(array $options = []): array
    {
        $conditions = ($options['isAuthor'] ?? false) ? ['admin::is-creator'] : [];

        // add plugin permissions for each role
        return array_map(PermissionDomain::create(...), [
            ['action' => 'plugin::upload.read', 'conditions' => $conditions],
            ['action' => 'plugin::upload.configure-view'],
            ['action' => 'plugin::upload.assets.create'],
            ['action' => 'plugin::upload.assets.update', 'conditions' => $conditions],
            ['action' => 'plugin::upload.assets.download'],
            ['action' => 'plugin::upload.assets.copy-link'],
        ]);
    }

    /**
     * Display a warning if the role superAdmin doesn't exist
     * or if the role is not assigned to at least one user.
     */
    public function displayWarningIfNoSuperAdmin(): void
    {
        $superAdminRole = $this->getSuperAdminWithUsersCount();
        /** @var User $userService */
        $userService = $this->strapi->service('admin::user');
        $someUsersExists = $userService->exists();

        if ($superAdminRole === null) {
            $this->strapi->log()->warning("Your application doesn't have a super admin role.");
        } elseif ($someUsersExists && ($superAdminRole['usersCount'] ?? 0) === 0) {
            $this->strapi->log()->warning("Your application doesn't have a super admin user.");
        }
    }

    /**
     * Assign permissions to a role.
     *
     * @param list<array<string, mixed>> $permissions permissions to assign to the role
     * @return list<array<string, mixed>>
     */
    public function assignPermissions(int|string $roleId, array $permissions = []): array
    {
        PermissionValidation::validatePermissionsExist($permissions);

        $permissionService = $this->permissionService();

        // Internal actions are not handled by the role service, so any permission
        // with an internal action is filtered out
        $internalActions = [];
        foreach ($permissionService->actionProvider->values() as $action) {
            if (($action['section'] ?? null) === 'internal') {
                $internalActions[] = $action['actionId'];
            }
        }

        /** @var Role $roleService */
        $roleService = $this->strapi->service('admin::role');
        $superAdmin = $roleService->getSuperAdmin();
        $isSuperAdmin = $superAdmin !== null && $superAdmin['id'] === $roleId;

        $permissionsWithRole = array_map(
            // Add the role attribute to every permission, then transform it into a Permission instance
            static fn (array $permission): array => PermissionDomain::create([...$permission, 'role' => $roleId]),
            $permissions,
        );

        $existingPermissions = $permissionService->findMany([
            'where' => ['role' => ['id' => $roleId]],
            'populate' => ['role'],
        ]);

        $isNotInternal = static fn (array $permission): bool => !in_array($permission['action'] ?? null, $internalActions, true);

        $permissionsToAdd = array_values(array_filter(
            self::differenceWith($permissionsWithRole, $existingPermissions),
            $isNotInternal,
        ));

        $permissionsToDelete = array_values(array_filter(
            self::differenceWith($existingPermissions, $permissionsWithRole),
            $isNotInternal,
        ));

        // lodash/fp differenceBy('id', permissionsToDelete, existingPermissions): `permissionsToDelete`
        // minus `existingPermissions` (by id), i.e. empty — only newly created permissions are returned
        $existingIds = array_map(static fn (array $p): mixed => $p['id'] ?? null, $existingPermissions);
        $permissionsToReturn = array_values(array_filter(
            $permissionsToDelete,
            static fn (array $p): bool => !in_array($p['id'] ?? null, $existingIds, true),
        ));

        if (count($permissionsToDelete) > 0) {
            $permissionService->deleteByIds(array_map(static fn (array $p): mixed => $p['id'], $permissionsToDelete));
        }

        if (count($permissionsToAdd) > 0) {
            $newPermissions = $this->addPermissions($roleId, $permissionsToAdd);
            array_push($permissionsToReturn, ...$newPermissions);
        }

        if (!$isSuperAdmin && (count($permissionsToAdd) > 0 || count($permissionsToDelete) > 0)) {
            /** @var Metrics $metrics */
            $metrics = $this->strapi->service('admin::metrics');
            $metrics->sendDidUpdateRolePermissions();
        }

        if (count($permissionsToAdd) > 0 || count($permissionsToDelete) > 0) {
            /** @var ApiToken $apiTokenAdmin */
            $apiTokenAdmin = $this->strapi->service('admin::api-token-admin');
            $apiTokenAdmin->syncPermissionsForRole($roleId);
        }

        return $permissionsToReturn;
    }

    /**
     * lodash/fp `differenceWith(arePermissionsEqual, $values, $others)`.
     *
     * @param list<array<string, mixed>> $values
     * @param list<array<string, mixed>> $others
     * @return list<array<string, mixed>>
     */
    private static function differenceWith(array $values, array $others): array
    {
        return array_values(array_filter($values, static function (array $value) use ($others): bool {
            foreach ($others as $other) {
                if (self::arePermissionsEqual($value, $other)) {
                    return false;
                }
            }

            return true;
        }));
    }

    /**
     * @param list<array<string, mixed>> $permissions
     * @return list<array<string, mixed>>
     */
    public function addPermissions(int|string $roleId, array $permissions): array
    {
        $permissionService = $this->permissionService();
        $conditionProvider = $permissionService->conditionProvider;

        $permissionsWithRole = array_map(
            static fn (array $permission): array => PermissionDomain::create(
                PermissionDomain::sanitizeConditions($conditionProvider, [...$permission, 'role' => $roleId]),
            ),
            $permissions,
        );

        return $permissionService->createMany(array_values($permissionsWithRole));
    }

    /** @param array<string, mixed> $action */
    private static function isContentTypeAction(array $action): bool
    {
        return ($action['section'] ?? null) === self::CONTENT_TYPE_SECTION;
    }

    /** Reset super admin permissions (giving it all permissions). */
    public function resetSuperAdminPermissions(): void
    {
        /** @var Role $roleService */
        $roleService = $this->strapi->service('admin::role');
        $superAdminRole = $roleService->getSuperAdmin();
        if ($superAdminRole === null) {
            return;
        }

        $permissionService = $this->permissionService();
        /** @var ContentType $contentTypeService */
        $contentTypeService = $this->strapi->service('admin::content-type');

        $allActions = $permissionService->actionProvider->values();

        $contentTypesActions = array_values(array_filter($allActions, self::isContentTypeAction(...)));
        $otherActions = array_values(array_filter($allActions, static fn (array $action): bool => !self::isContentTypeAction($action)));

        // First, get the content-types permissions
        $permissions = $contentTypeService->getPermissionsWithNestedFields($contentTypesActions);

        // Then add every other permission
        foreach ($otherActions as $action) {
            $actionId = $action['actionId'];
            $subjects = $action['subjects'] ?? null;

            if (is_array($subjects)) {
                foreach ($subjects as $subject) {
                    $permissions[] = PermissionDomain::create(['action' => $actionId, 'subject' => $subject]);
                }
            } else {
                $permissions[] = PermissionDomain::create(['action' => $actionId]);
            }
        }

        /** @var list<array<string, mixed>> $transformedPermissions */
        $transformedPermissions = $this->hooks['willResetSuperAdminPermissions']->call($permissions);

        $this->assignPermissions($superAdminRole['id'], $transformedPermissions);
    }

    /**
     * Check if a user object includes the super admin role.
     *
     * @param array<string, mixed> $user
     */
    public function hasSuperAdminRole(array $user): bool
    {
        $roles = is_array($user['roles'] ?? null) ? $user['roles'] : [];

        foreach ($roles as $role) {
            if (is_array($role) && ($role['code'] ?? null) === self::SUPER_ADMIN_CODE) {
                return true;
            }
        }

        return false;
    }
}
