<?php

declare(strict_types=1);

namespace Strapi\Cli\Node\Vite;

/**
 * Port of packages/core/strapi/src/node/vite/config.ts (`resolveProductionConfig`,
 * `mergeConfigWithUserConfig`).
 *
 * Vite runs in Node, so the configuration is written as a JavaScript module
 * (`.strapi/client/vite.config.mjs`) that mirrors upstream's `resolveBaseConfig` +
 * `resolveProductionConfig`: same `define`, `optimizeDeps.include`, `resolve.dedupe` and the
 * `strapi/server/build-files` plugin emitting the `index.html` with the hashed entry. A user
 * `src/admin/vite.config.{js,mjs,ts}` exporting a `(config) => config` function is applied.
 *
 * @phpstan-import-type BuildContext from \Strapi\Cli\Node\CreateBuildContext
 */
final class Config
{
    public const USER_CONFIGS = ['vite.config.js', 'vite.config.mjs', 'vite.config.ts', 'vite.config.mts'];

    public const ADMIN_VITE_ALIAS_MODULES = [
        'react', 'react-dom', 'react-router-dom', 'styled-components', 'react-redux', '@reduxjs/toolkit',
        '@strapi/design-system', '@radix-ui/react-tooltip', 'lodash', 'invariant', 'prismjs',
        'react-dnd', 'react-dnd-html5-backend',
    ];

    public const ADMIN_VITE_DEDUPE_MODULES = [...self::ADMIN_VITE_ALIAS_MODULES, '@strapi/strapi'];

    /**
     * The JavaScript source of the Vite config module for a production build.
     *
     * @param BuildContext $ctx
     */
    public static function resolveProductionConfig(array $ctx): string
    {
        $minify = ($ctx['options']['minify'] ?? true) !== false;
        $sourcemap = (bool) ($ctx['options']['sourcemap'] ?? false);
        $isMonorepoExampleApp = $ctx['strapi']->config()->get('uuid') === 'getstarted' || $ctx['strapi']->config()->get('info.strapi.uuid') === 'getstarted';

        $userConfig = self::findUserConfig($ctx);

        $json = static fn (mixed $value): string => (string) json_encode($value, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);

        $include = [
            'react', 'react/jsx-runtime', 'react-dom/client', 'styled-components', 'react-router-dom',
            'react-redux', '@reduxjs/toolkit', '@strapi/design-system', '@radix-ui/react-tooltip',
            'lodash', 'invariant', 'prismjs',
        ];
        if ($isMonorepoExampleApp) {
            $include = [...$include, '@dnd-kit/core', '@dnd-kit/sortable', '@dnd-kit/utilities', '@dnd-kit/modifiers',
                '@radix-ui/react-toolbar', 'codemirror5', 'codemirror5/addon/display/placeholder', 'date-fns-tz',
                'date-fns/format', 'date-fns/formatISO', 'highlight.js', 'lodash/capitalize', 'lodash/groupBy',
                'lodash/has', 'lodash/isNil', 'lodash/locale', 'lodash/map', 'lodash/mapValues', 'lodash/pull',
                'lodash/size', 'lodash/sortBy', 'lodash/tail', 'lodash/toLower', 'lodash/toNumber', 'lodash/toString',
                'lodash/truncate', 'lodash/uniq', 'lodash/upperFirst', 'markdown-it', 'markdown-it-abbr',
                'markdown-it-container', 'markdown-it-deflist', 'markdown-it-emoji', 'markdown-it-footnote',
                'markdown-it-ins', 'markdown-it-mark', 'markdown-it-sub', 'markdown-it-sup', 'react-colorful',
                'react-dnd-html5-backend', 'react-window', 'semver', 'semver/functions/lt', 'semver/functions/valid',
                'slate', 'slate-history', 'slate-react', 'motion'];
        }

        $entryHtml = self::documentHtmlTemplate();

        $userImport = $userConfig !== null ? "import userConfig from " . $json(self::toFileUrl($userConfig)) . ";\n" : '';
        $applyUser = $userConfig !== null ? "const resolved = typeof userConfig === 'function' ? userConfig(config) : (userConfig?.default ? userConfig.default(config) : config);\n" : "const resolved = config;\n";

        return <<<JS
// This file was automatically generated by Strapi (strapi/strapi, node/vite/config.php).
// Any modifications made will be discarded.
import { createRequire } from 'node:module';
import path from 'node:path';
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react-swc';
{$userImport}
const require = createRequire(import.meta.url);
const cwd = {$json($ctx['cwd'])};
const basePath = {$json($ctx['basePath'])};
const entry = {$json($ctx['entry'])};
const env = {$json($ctx['env'])};
const target = {$json(self::browserslistToEsbuild($ctx['target']))};

const resolveAlias = (mod) => {
  try {
    return path.dirname(require.resolve(mod + '/package.json', { paths: [cwd] }));
  } catch {
    return null;
  }
};
const alias = Object.fromEntries(
  {$json(self::ADMIN_VITE_ALIAS_MODULES)}
    .map((mod) => [mod, resolveAlias(mod)])
    .filter(([, dir]) => dir !== null)
);

const documentHtml = (entryPath) => {$json($entryHtml)}.replace('__ENTRY__', entryPath);

// the `strapi/server/build-files` plugin of upstream vite/plugins.ts (flag-off build)
const buildFilesPlugin = () => {
  const CHUNK_ID = '.strapi/client/app.js';
  return {
    name: 'strapi/server/build-files',
    apply: 'build',
    buildStart() {
      this.emitFile({ type: 'chunk', id: CHUNK_ID, name: 'strapi' });
    },
    generateBundle(_options, bundle) {
      const entryFile = Object.values(bundle).find(
        (file) => file.type === 'chunk' && file.name === 'strapi' && file.facadeModuleId?.endsWith(CHUNK_ID)
      );
      if (!entryFile) {
        throw new Error(`Failed to find entry file in bundle (\${CHUNK_ID})`);
      }
      const entryPath = [basePath.replace(/\\/+\$/, ''), entryFile.fileName].join('/');
      this.emitFile({ type: 'asset', fileName: 'index.html', source: documentHtml(entryPath) });
    },
  };
};

const config = {
  root: cwd,
  base: basePath,
  publicDir: false,
  logLevel: 'silent',
  mode: 'production',
  build: {
    emptyOutDir: false,
    outDir: {$json($ctx['distDir'])},
    target,
    assetsDir: '',
    minify: {$json($minify)},
    sourcemap: {$json($sourcemap)},
    rollupOptions: { input: { strapi: entry } },
  },
  cacheDir: 'node_modules/.strapi/vite',
  configFile: false,
  define: { process: {}, 'process.env': JSON.stringify(env) },
  envPrefix: 'STRAPI_ADMIN_',
  optimizeDeps: { include: {$json($include)} },
  resolve: { dedupe: {$json(self::ADMIN_VITE_DEDUPE_MODULES)}, alias },
  plugins: [react(), buildFilesPlugin()],
};

{$applyUser}
export default defineConfig(resolved);
JS;
    }

    /** @param BuildContext $ctx */
    public static function findUserConfig(array $ctx): ?string
    {
        foreach (self::USER_CONFIGS as $file) {
            $filePath = $ctx['appDir'] . '/src/admin/' . $file;
            if (is_file($filePath)) {
                return $filePath;
            }
        }

        return null;
    }

    private static function toFileUrl(string $path): string
    {
        return 'file://' . str_replace('\\', '/', $path);
    }

    /**
     * browserslist-to-esbuild for the default list: the esbuild targets it yields for
     * "last 3 major versions, Firefox ESR, last 2 Opera versions, not dead" (checked in at build time).
     *
     * @param list<string> $browserslist
     * @return list<string>
     */
    public static function browserslistToEsbuild(array $browserslist): array
    {
        // A custom list cannot be evaluated without the browserslist database: use esbuild's `modules` default.
        if ($browserslist !== \Strapi\Cli\Node\CreateBuildContext::DEFAULT_BROWSERSLIST) {
            return ['es2020', 'edge88', 'firefox78', 'chrome87', 'safari14'];
        }

        return ['chrome120', 'edge120', 'firefox115', 'ios16', 'opera104', 'safari16'];
    }

    /** The DefaultDocument markup with an `__ENTRY__` placeholder. */
    private static function documentHtmlTemplate(): string
    {
        $logger = new \Strapi\Cli\Cli\Utils\Logger(silent: true);

        return \Strapi\Cli\Node\StaticFiles::getDocumentHTML($logger, ['entryPath' => '__ENTRY__']);
    }
}
