<?php

declare(strict_types=1);

namespace Strapi\Cli\Node;

use Strapi\Cli\Cli\Utils\Logger;

/**
 * Port of packages/core/strapi/src/node/staticFiles.ts: the generated `.strapi/client/app.js`
 * entry module, `index.html` document and (flag on) `styles.css` stylesheet.
 *
 * `index.html` is the markup of `@strapi/admin`'s `DefaultDocument` component rendered by hand
 * (upstream uses react-dom/server): same head, `#strapi` mount node and `<noscript>` fallback.
 *
 * @phpstan-import-type BuildContext from CreateBuildContext
 */
final class StaticFiles
{
    private const AUTO_GENERATED_WARNING = "This file was automatically generated by Strapi.\nAny modifications made will be discarded.";

    /** @param BuildContext $ctx */
    public static function getStylesheet(array $ctx): string
    {
        return "/**\n * This file was automatically generated by Strapi.\n * Any modifications made will be discarded.\n */\n@import '@strapi/strapi/admin/styles.css';\n";
    }

    /** @param BuildContext $ctx */
    public static function getEntryModule(array $ctx): string
    {
        $pluginsObject = implode(",\n", array_map(static fn (array $p): string => "'{$p['name']}': {$p['importName']}", $ctx['plugins']));

        $pluginsImport = implode("\n", array_map(static fn (array $p): string => "import {$p['importName']} from '{$p['modulePath']}';", $ctx['plugins']));

        $customisations = $ctx['customisations'];
        $features = $ctx['features'];

        $lines = [
            '/**',
            ' * This file was automatically generated by Strapi.',
            ' * Any modifications made will be discarded.',
            ' */',
            $ctx['nextDesignSystem'] ? "import './styles.css';" : '',
            $pluginsImport,
            'import { renderAdmin } from "@strapi/strapi/admin"',
            '',
            $customisations !== null ? "import customisations from '{$customisations['modulePath']}'" : '',
            '',
            'renderAdmin(',
            '  document.getElementById("strapi"),',
            '  {',
            $customisations !== null ? '    customisations,' : '',
            $features !== null && $features !== [] ? '    features: ' . json_encode($features, JSON_UNESCAPED_SLASHES) . ',' : '',
            '    plugins: {',
            $pluginsObject,
            '    }',
            '  })',
        ];

        return implode("\n", array_filter($lines, static fn (string $line): bool => $line !== '')) . "\n";
    }

    /**
     * The `DefaultDocument` of @strapi/admin as static markup.
     *
     * @param array{entryPath?: string} $props
     */
    public static function getDocumentHTML(Logger $logger, array $props = []): string
    {
        $entryPath = $props['entryPath'] ?? null;
        $globalStyles = "\n  html,\n  body,\n  #strapi {\n    height: 100%;\n  }\n  body {\n    margin: 0;\n    -webkit-font-smoothing: antialiased;\n  }\n";

        $script = $entryPath !== null ? '<script type="module" src="' . htmlspecialchars($entryPath, ENT_QUOTES) . '"></script>' : '';

        $html = '<!DOCTYPE html><html lang="en"><head><meta charSet="utf-8"/>'
            . '<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"/>'
            . '<meta name="robots" content="noindex"/><meta name="referrer" content="same-origin"/>'
            . '<title>Strapi Admin</title><style>' . $globalStyles . '</style></head>'
            . '<body><div id="strapi"></div>' . self::noJavascript() . $script . '</body></html>';

        $logger->debug('Rendered the HTML');

        return $html;
    }

    /** The `NoJavascript` component of @strapi/admin. */
    private static function noJavascript(): string
    {
        return '<noscript><div style="display:flex;align-items:center;justify-content:center;height:100%;font-family:sans-serif;">'
            . '<div style="text-align:center;"><h1>JavaScript disabled</h1>'
            . '<p>Please <a href="https://www.enable-javascript.com/" target="_blank" rel="noopener noreferrer">enable JavaScript</a> in your browser and reload the page to proceed.</p>'
            . '</div></div></noscript>';
    }

    /**
     * Because we now auto-generate the index.html file, we should be clear that people _should not_ modify it.
     *
     * @internal
     */
    public static function decorateHTMLWithAutoGeneratedWarning(string $htmlTemplate): string
    {
        return (string) preg_replace('/<head/', "\n<!--\n" . self::AUTO_GENERATED_WARNING . "\n-->\n<head", $htmlTemplate, 1);
    }

    /**
     * Creates the `.strapi/client` folder with `app.js` (the entry module), `index.html` and,
     * when the next design system flag is on, `styles.css`.
     *
     * @param BuildContext $ctx
     */
    public static function writeStaticClientFiles(array $ctx): void
    {
        $runtimeDir = $ctx['runtimeDir'];
        if (!is_dir($runtimeDir)) {
            mkdir($runtimeDir, 0o777, true);
        }
        $ctx['logger']->debug('Created the runtime directory');

        $indexHtml = self::decorateHTMLWithAutoGeneratedWarning(self::getDocumentHTML(
            $ctx['logger'],
            $ctx['bundler'] === 'vite' ? ['entryPath' => '/' . $ctx['entry']] : [],
        ));

        file_put_contents($runtimeDir . '/index.html', self::prettyHtml($indexHtml));
        $ctx['logger']->debug('Wrote the index.html file');

        file_put_contents($runtimeDir . '/app.js', self::getEntryModule($ctx));
        $ctx['logger']->debug('Wrote the admin.js file');

        if ($ctx['nextDesignSystem']) {
            file_put_contents($runtimeDir . '/styles.css', self::getStylesheet($ctx));
            $ctx['logger']->debug('Wrote the styles.css file');
        }
    }

    /** A light stand-in for prettier's html formatting: one tag per line. */
    private static function prettyHtml(string $html): string
    {
        $html = (string) preg_replace('/>(?=<)/', ">\n", $html);

        return rtrim($html) . "\n";
    }
}
