<?php

declare(strict_types=1);

namespace Strapi\Cli\Tests\Node;

use PHPUnit\Framework\TestCase;
use Strapi\Cli\Cli\Utils\Logger;
use Strapi\Cli\Node\StaticFiles;

/** Port of packages/core/strapi/src/node/__tests__/staticFiles.test.ts (entry module and document). */
final class StaticFilesTest extends TestCase
{
    /** @return array<string, mixed> */
    private static function ctx(array $overrides = []): array
    {
        return [
            'appDir' => '/app',
            'adminPath' => '/admin',
            'basePath' => '/admin/',
            'bundler' => 'vite',
            'customisations' => null,
            'cwd' => '/app',
            'distDir' => 'build',
            'distPath' => '/app/build',
            'entry' => '.strapi/client/app.js',
            'env' => [],
            'features' => null,
            'logger' => Logger::createLogger(['silent' => true]),
            'nextDesignSystem' => false,
            'options' => [],
            'plugins' => [],
            'runtimeDir' => '/app/.strapi/client',
            'scanRoots' => [],
            'target' => [],
            ...$overrides,
        ];
    }

    public function testEntryModuleWithoutPlugins(): void
    {
        $js = StaticFiles::getEntryModule(self::ctx());

        self::assertStringContainsString('import { renderAdmin } from "@strapi/strapi/admin"', $js);
        self::assertStringContainsString('document.getElementById("strapi")', $js);
        self::assertStringContainsString("plugins: {\n    }", $js);
        self::assertStringNotContainsString('customisations', $js);
        self::assertStringNotContainsString('styles.css', $js);
    }

    public function testEntryModuleWithPluginsCustomisationsAndFeatures(): void
    {
        $js = StaticFiles::getEntryModule(self::ctx([
            'plugins' => [
                ['name' => 'content-manager', 'importName' => 'contentManager', 'type' => 'module', 'modulePath' => '@strapi/content-manager/strapi-admin'],
                ['name' => 'my-plugin', 'importName' => 'myPlugin', 'type' => 'local', 'modulePath' => '../../src/plugins/my-plugin/strapi-admin'],
            ],
            'customisations' => ['path' => '/app/src/admin/app.js', 'modulePath' => '../../src/admin/app.js'],
            'features' => ['future' => ['unstableNextDesignSystem' => false]],
            'nextDesignSystem' => true,
        ]));

        self::assertStringContainsString("import './styles.css';", $js);
        self::assertStringContainsString("import contentManager from '@strapi/content-manager/strapi-admin';", $js);
        self::assertStringContainsString("import myPlugin from '../../src/plugins/my-plugin/strapi-admin';", $js);
        self::assertStringContainsString("import customisations from '../../src/admin/app.js'", $js);
        self::assertStringContainsString('customisations,', $js);
        self::assertStringContainsString('features: {"future":{"unstableNextDesignSystem":false}},', $js);
        self::assertStringContainsString("'content-manager': contentManager,\n'my-plugin': myPlugin", $js);
    }

    public function testDocumentHtml(): void
    {
        $html = StaticFiles::getDocumentHTML(Logger::createLogger(['silent' => true]), ['entryPath' => '/.strapi/client/app.js']);

        self::assertStringStartsWith('<!DOCTYPE html><html lang="en">', $html);
        self::assertStringContainsString('<title>Strapi Admin</title>', $html);
        self::assertStringContainsString('<div id="strapi"></div>', $html);
        self::assertStringContainsString('<noscript>', $html);
        self::assertStringContainsString('<script type="module" src="/.strapi/client/app.js"></script>', $html);
        self::assertStringContainsString('<meta name="robots" content="noindex"/>', $html);

        $noEntry = StaticFiles::getDocumentHTML(Logger::createLogger(['silent' => true]));
        self::assertStringNotContainsString('<script', $noEntry);

        $decorated = StaticFiles::decorateHTMLWithAutoGeneratedWarning($html);
        self::assertStringContainsString("<!--\nThis file was automatically generated by Strapi.\nAny modifications made will be discarded.\n-->\n<head", $decorated);
    }

    public function testWriteStaticClientFiles(): void
    {
        $dir = sys_get_temp_dir() . '/strapi-static-' . bin2hex(random_bytes(4));
        $ctx = self::ctx(['cwd' => $dir, 'runtimeDir' => $dir . '/.strapi/client']);

        StaticFiles::writeStaticClientFiles($ctx);

        self::assertFileExists($dir . '/.strapi/client/app.js');
        self::assertFileExists($dir . '/.strapi/client/index.html');
        self::assertFileDoesNotExist($dir . '/.strapi/client/styles.css');
        self::assertStringContainsString('src="/.strapi/client/app.js"', (string) file_get_contents($dir . '/.strapi/client/index.html'));

        unlink($dir . '/.strapi/client/app.js');
        unlink($dir . '/.strapi/client/index.html');
        rmdir($dir . '/.strapi/client');
        rmdir($dir . '/.strapi');
        rmdir($dir);
    }
}
